### PR TITLE
@kawacchu joined as a maintainer 🎉

### PR DESCRIPTION
**Pull request by kmyk**
close https://github.com/kmyk/online-judge-tools/issues/601

@kawacchu is now a maintainer!
This pull request update some documents for this.

---

@kawacchu please check this pull request and merge if there is no problem.

### CODE REVIEW

**Comment by kawacchu** [comment]
It looks good to me.

However, I couldn't find the version format `?.?.?` in [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
Do you intend to revise `?.?.?` to `NEXT_VERSION` when it is out?

**Comment by kawacchu** [comment]
It looks good to me.

However, I couldn't find the version format `?.?.?` in [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
Do you intend to revise `?.?.?` to `NEXT_VERSION` when it is out?

**Comment by kmyk** [comment]
まだバージョン番号が確定してない場合をどう書くかに困って適当にしてしまったけれど、 keepachangelog.com によると `Unreleased` が推奨のようなのでそのようにしました (https://keepachangelog.com/ja/1.0.0/#effort)
普段は CHANGELOG はリリース時にしか触ってないのだけれど、メンテナの話は重要なので先に CHANGELOG に書いておきたい気がしたためこうなりました。

**Comment by kawacchu** [comment]
I overlooked this. We follow this recommendation.

**Pull request merged**
